PROGRAM test_itp2

USE MD_linear_ITP
!USE MD_LINEAR_ITP

IMPLICIT NONE

CHARACTER (LEN=120) :: INPUT_PATH
CHARACTER (LEN=120) :: OUTPUT_PATH

!INPUT_NUMBER AND OUTPUT_NUMBER
INTEGER, PARAMETER :: I_N = 6
INTEGER, PARAMETER :: O_N =  2 *I_N-1

!INPUT_VALUE AND OUPUT_VALUE
REAL*8, DIMENSION(1:I_N) :: I_V 
REAL*8, DIMENSION(1:O_N) :: O_V 

INTEGER :: I

REAL*8 :: N_ITP = 2.0

!INPUT_PATH = "/home/changwan/INTERPOLATION/HILBERT_STACKED_A_GPR.txt"
INPUT_PATH = "/home/changwan/INTERPOLATION/input_values.txt"


OUTPUT_PATH = "/home/changwan/INTERPOLATION/output_values.txt"


OPEN(UNIT=10, FILE=INPUT_PATH, FORM='FORMATTED' &
     , STATUS='OLD',ACTION='READ')
OPEN(UNIT=20, FILE=OUTPUT_PATH, STATUS='REPLACE' &
     , ACTION='WRITE')

READ(10,*) I_V

CALL  linear(N_ITP,I_N, I_V, O_N, O_V)

DO I =1, O_N
   WRITE(20,*) O_V(I)
END DO


!PRINT *, T_V
END PROGRAM
