PROGRAM interpolation
IMPLICIT NONE

CHARACTER (LEN=120) :: INPUT_PATH
CHARACTER (LEN=120) :: OUTPUT_PATH

!INPUT_NUMBER AND OUTPUT_NUMBER
INTEGER, PARAMETER :: I_N = 6
INTEGER, PARAMETER :: O_N = 12

!INPUT_VALUE AND OUPUT_VALUE
REAL*8, DIMENSION(1:I_N) :: I_V 
REAL*8, DIMENSION(1:O_N) :: T_V 
REAL*8, DIMENSION(1:O_N) :: O_V 

INTEGER :: I
REAL*8 ::  SLOPE
REAL*8 ::  Y_ITC

INPUT_PATH = "/home/changwan/INTERPOLATION/input_values.txt"
OUTPUT_PATH = "/home/changwan/INTERPOLATION/output_values.txt"


OPEN(UNIT=10, FILE=INPUT_PATH, FORM='FORMATTED' &
     , STATUS='OLD',ACTION='READ')
OPEN(UNIT=20, FILE=OUTPUT_PATH, STATUS='REPLACE' &
     , ACTION='WRITE')

READ(10,*) I_V

T_V(1) = I_V(1)
T_V(O_N) = I_V(I_N)

!CALCULATE THE SLOPE
SLOPE = ( T_V(O_N) - T_V(1) ) / (O_N - 1)

!CALCULATE Y-INTERCEPT
Y_ITC = T_V(1) - SLOPE * 1

PRINT *, T_V(1), T_V(O_N), SLOPE, Y_ITC


DO I = 1,O_N
   T_V(I) = SLOPE * I + Y_ITC
END DO

O_V = T_V

!OUTPUT

DO I=1,O_N
   WRITE(20,*) O_V(I)
END DO

PRINT *, T_V(1), T_V(O_N), SLOPE, Y_ITC
!PRINT *, T_V
END PROGRAM
